# Generated by Django 3.2.8 on 2022-01-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Contactnumber', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=10)),
                ('ProfilePicture', models.ImageField(upload_to=None)),
            ],
        ),
    ]
